{% set version = "1.0.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vdiffr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vdiffr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vdiffr/vdiffr_{{ version }}.tar.gz
  sha256: ed432e5b67ee8b08e1aab5f7edb89da74e768da68ae6c6e2be483fcc354952d2

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cpp11
    - r-diffobj
    - r-glue
    - r-htmltools
    - r-lifecycle
    - r-rlang
    - r-testthat >=3.0.0
    - r-xml2 >=1.0.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cpp11
    - r-diffobj
    - r-glue
    - r-htmltools
    - r-lifecycle
    - r-rlang
    - r-testthat >=3.0.0
    - r-xml2 >=1.0.0

test:
  commands:
    - $R -e "library('vdiffr')"           # [not win]
    - "\"%R%\" -e \"library('vdiffr')\""  # [win]

about:
  home: https://github.com/r-lib/vdiffr
  license: MIT
  summary: An extension to the 'testthat' package that makes it easy to add graphical unit tests. It provides a Shiny application to manage the test cases.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
